/*
 * This source file was generated by the Gradle 'init' task
 */
package logica;

import igu.Principal;

public class App {

    public static void main(String[] args) {
        Principal ventana = new Principal();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }
}